### ISSUE TITLE
ModuleNotFoundError: No module named 'toolstr.charts'

### ISSUE THREAD

**Issue by gcamilo** [fei-protocol/checkthechain#1]
When running `ctc setup` after successfully installing checkthechain I get the following error:

`ModuleNotFoundError: No module named 'toolstr.charts'`

Seems like maybe the wrong version of toolstr is depended on by the package? Looks like a great tool by the way!

**Comment by sslivkoff** [comment]
hi @gcamilo :wave: 

yea it looks like an old version of toolstr there. this was fixed in a recent commit. for now you can run `pip install -U toolstr` to upgrade toolstr. can also upgrade ctc with `pip install -U checkthechain`

please report back if that doesnt fix it

**Comment by sslivkoff** [comment]
hmmm it seems the source distribution of toolstr is not working properly. will push out a fix soon. thanks for reporting

**Comment by gcamilo** [comment]
Happy to help.

**Comment by sslivkoff** [comment]
ok, a4cf8e95b55bc226c80c075631e6b21d06da61fc should fix this. toolstr's setup.py wasnt properly finding all packages, latest version now does

updating ctc (now at 0.2.8) with `pip install -U checkthecheck` should fix everything 😎😎

**Comment by gcamilo** [comment]
All good! Thanks for the quick fix.
