### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by devtooligan** [fei-protocol/checkthechain#17]
any help on this?  fwiw this is a fairly new m1 and i havent done anything in python on it until now

[log.log](https://github.com/fei-protocol/checkthechain/files/8457703/log.log)

**Comment by sslivkoff** [comment]
hi devtooligan

I dont have an m1 to try this on. looks like a matplotlib install issue (matplotlib is removed in latest commit but not in any pypi releases yet). can you try the steps listed here and see if they fix it https://stackoverflow.com/a/66456204

**Comment by devtooligan** [comment]
tried it.  no dice.

i guess ill wait for the pypi release.  thanks for buidling this btw, looks cool

**Comment by rafaelugolini** [comment]
@devtooligan do you still have the issue? I have m1 and running without any problem

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by StayFoolisj** [comment]
@rafaelugolini I just tried to install but failing, do you remember how you installed it? After installation, running setup and finally running `ctc` I get this:
```
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
```

**Comment by rafaelugolini** [comment]
@StayFoolisj can you give more details of your env?

**Comment by StayFoolisj** [comment]
Got it working
