### ISSUE TITLE
`ctc setup` error

### ISSUE THREAD

**Issue by kryptoklob** [fei-protocol/checkthechain#25]
Env: Win11 + WSL (Ubuntu)
Python: 2.7.18
Pip: 20.0.2

After building from master, I `cd` into the `scripts` folder and run the following:

```
caleb@CORUSCANT:~$ ctc setup
'type' object is not subscriptable
```

I attempted to fix the error potentially by deleteing my ctc config folder. Same error.

**Comment by rcstanciu** [comment]
I believe `ctc` requires min. python 3.7

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
