### ISSUE TITLE
Fails to run with version `0.3.0b1`

### ISSUE THREAD

**Issue by amanusk** [fei-protocol/checkthechain#26]
Could be my python version (3.8), but the cli fails to run due to a problem parsing the version.
Getting the error:

`invalid literal for int() with base 10: '0b1'`

Changing the  version to something like `0.3.2` fixes it (requires removing the config and running the setup again)

**Comment by sslivkoff** [comment]
fix coming soon with upcoming 0.3.0 release

thanks for the patience

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by sslivkoff** [comment]
resolved, the `b` is no longer in the version name
