### ISSUE TITLE
'more than one match found in sequence' when having additional RPC provider

### ISSUE THREAD

**Issue by fala13** [fei-protocol/checkthechain#39]
Hi,

new user here. I keep getting 'more than one match found in sequence'  (probably this): https://github.com/fei-protocol/checkthechain/blob/55cdad220d106a16205f8299fc3ad595cb36ba07/src/ctc/toolbox/search_utils.py#L66 
for various commands, e.g.

Some random USDC tx:
```
ctc 0x65dacb1027ed5aaf82daa98a449151fe77bb10e73727c4823e388710bb7eb33d
┌─────────────────────┐
│ Transaction Summary │
└─────────────────────┘
- hash: 0x65dacb1027ed5aaf82daa98a449151fe77bb10e73727c4823e388710bb7eb33d
- from: 0x6c6b6b70c31edfd9c0fb8070c713c06ee687aad2
- to: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
- block number: 15648723
- transaction index: 76
- nonce: 15
- type: legacy (0)
- call data length: 138
more than one match found in sequence
```
WETH withdrawals:
```
ctc events 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 Withdrawal
more than one match found in sequence
```

Using Python 3.10.4 & checkthechain==0.3.0 installed with pip within a conda 4.14.0 env.

btw. during installation had to do `ctc setup --overwrite`, otherwise the config file would not appear.

**Comment by fala13** [comment]
Found the issue - I entered two providers in ctc setup step, my local node  as the additional one. Once I removed my local node from providers list, the issue disappeared and both above queries run fine.

**Comment by fala13** [comment]
huh, now when I try adding my node again to the providers list it seems to work ok and I cannot reproduce the issue.

**Comment by sslivkoff** [comment]
thanks for filing this. not sure what exactly happened here but if you notice further issues please post them

the ctc test suite does not test any conda envs, not sure if that might be related. I have also received word from other users of issues when there are multiple providers for the same network. i will look into this
