### ISSUE TITLE
ctc dex chart always return this waning

### ISSUE THREAD

**Issue by 0xshandy** [fei-protocol/checkthechain#43]
ctc dex chart 0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8
getting events from node, block range: [15195555, 15666020]
/Users/dual/opt/anaconda3/envs/web3/lib/python3.9/site-packages/ctc/rpc/rpc_protocols/rpc_http_async.py:35: UserWarning: request failed with code 429 retrying in 1.8541545285809442s
  warnings.warn(
/Users/dual/opt/anaconda3/envs/web3/lib/python3.9/site-packages/ctc/rpc/rpc_protocols/rpc_http_async.py:35: UserWarning: request failed with code 429 retrying in 1.7716537108027812s
  warnings.warn(
/Users/dual/opt/anaconda3/envs/web3/lib/python3.9/site-packages/ctc/rpc/rpc_protocols/rpc_http_async.py:35: UserWarning: request failed with code 429 retrying in 1.0137542644038302s
  warnings.warn(
/Users/dual/opt/anaconda3/envs/web3/lib/python3.9/site-packages/ctc/rpc/rpc_protocols/rpc_http_async.py:35: UserWarning: request failed with code 429 retrying in 1.025351231137594s

**Comment by sslivkoff** [comment]
what RPC provider are you using?

**Comment by 0xshandy** [comment]
> what RPC provider are you using?

Infura, Sir

**Comment by sslivkoff** [comment]
unfortunately infura nodes are usually not beefy enough to support larger queries. using an alternative like alchemy or running your own node yields much better results. in the future ctc might have a smarter rate limiting mechanism to support infura but for now iinfura is not supported for most queries

**Comment by sslivkoff** [comment]
I will add a warning about use of infura nodes to the setup process but will close this issue for now

**Comment by 0xshandy** [comment]
> unfortunately infura nodes are usually not beefy enough to support larger queries. using an alternative like alchemy or running your own node yields much better results. in the future ctc might have a smarter rate limiting mechanism to support infura but for now iinfura is not supported for most queries

Thanks for your answer, by the way, ctc is a great tool, really love it!
