### ISSUE TITLE
Use vim as default editor if $EDITOR not set

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/checkthechain#5]
My shell doesn't set $EDITOR by default, but vim comes preloaded onto basically everything, so maybe use that?

**Comment by sslivkoff** [comment]
sort of fixed in 97ba1a58bef0e13bdc19eb5484f8d5fb78ed21af, at least for ubuntu / debian

`ctc config edit` is plumbing not porcelain tho, so for now I don't want to build a more comprehensive solution
