### ISSUE TITLE
Error: `(sqlite3.OperationalError) near "ON": syntax error`

### ISSUE THREAD

**Issue by eswak** [fei-protocol/checkthechain#57]
When I run any command, I get the error :

> (sqlite3.OperationalError) near "ON": syntax error

Googling seems to indicate an incompatibly SQLite version (version >=3.24 needed)

When I run `python3.8 -c "import sqlite3; print(sqlite3.sqlite_version)"` I get : `3.22.0`

Running this command solves the issue :

> sudo apt-get install sqlite3

This updated sqlite3 to `3.31.1` and now everything works fine

I'm using WSL

**Comment by sslivkoff** [comment]
thanks for the report

the `ON` syntax is used for upserts into the sqlite db

sqlite is bundled as a system package not a python package so an automated fix isnt possible

added a sqlite version check during the ctc setup with an error message that shows your solution in 879cc9b968b0661a11007098cba76aa99bc03b2b
